import os
import datetime
import random
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mocking the Agent's "GoogleSearchTool" capability for the CI environment
class GoogleSearchTool:
    def search(self, query):
        # In a real scenario, this would call the Google Search API
        # For this demo, we return a simulated trending topic
        trends = ["AI in Healthcare", "Crypto Market Volatility", "Climate Change Data 2024", "EV Sales Trends"]
        return random.choice(trends)

def run_mission():
    print("🤖 Agent Activated: Starting Weekly Trend Analysis...")
    
    # 1. Trend Discovery
    search_tool = GoogleSearchTool()
    topic = search_tool.search("latest global trends data")
    print(f"🔍 Trend Identified: {topic}")
    
    # 2. Directory Setup
    today = datetime.datetime.now().strftime("%Y%m%d")
    sanitized_topic = topic.replace(" ", "_")
    base_dir = f"projects/{today}_{sanitized_topic}"
    
    os.makedirs(f"{base_dir}/data", exist_ok=True)
    os.makedirs(f"{base_dir}/plots", exist_ok=True)
    os.makedirs(f"{base_dir}/reports", exist_ok=True)
    os.makedirs(f"{base_dir}/scripts", exist_ok=True)
    
    print(f"📂 Created Workspace: {base_dir}")

    # 3. Data Simulation (Since we can't truly scrape in this restricted CI demo)
    # We generate a synthetic dataset based on the topic to demonstrate the pipeline
    print("⬇️  Fetching/Generating Data...")
    data = {
        'Category': ['A', 'B', 'C', 'D', 'E'],
        'Value': [random.randint(10, 100) for _ in range(5)],
        'Growth': [random.random() for _ in range(5)]
    }
    df = pd.DataFrame(data)
    csv_path = f"{base_dir}/data/dataset.csv"
    df.to_csv(csv_path, index=False)
    print(f"💾 Data Saved: {csv_path}")

    # 4. Analysis & Visualization
    print("📊 Generating Visualizations...")
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(10, 6))
    sns.barplot(x='Category', y='Value', data=df, palette='viridis')
    plt.title(f"Analysis of {topic}: Key Indicators")
    plt.savefig(f"{base_dir}/plots/trend_analysis.png")
    plt.close()

    # 5. Report Generation
    print("📝 Writing Insight Report...")
    report_content = f"""# 🧠 Weekly Trend Analysis: {topic}

## 📌 6W1H Summary
- **Who**: Automated Agent
- **When**: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Where**: Simulated Trend Data
- **What**: Automated analysis of {topic}
- **Why**: Weekly trend monitoring pipeline
- **How**: GitHub Actions + Python Script
- **Results**: 
  - Data: `{base_dir}/data/dataset.csv`
  - Plot: `{base_dir}/plots/trend_analysis.png`

## 1. Analysis
The agent identified **{topic}** as a key trending topic. 
Preliminary data suggests significant activity in Category **{df.loc[df['Value'].idxmax()]['Category']}**.

![Trend Chart](../plots/trend_analysis.png)

## 2. Conclusion
This report was automatically generated by the CI/CD pipeline.
"""
    with open(f"{base_dir}/reports/insight_report.md", "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print("✅ Mission Complete!")

if __name__ == "__main__":
    run_mission()
